# Generated by Django 4.0 on 2021-12-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmain',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='formmain',
            name='userid',
        ),
        migrations.AddField(
            model_name='formmain',
            name='csvfile',
            field=models.FileField(blank=True, upload_to='csvs'),
        ),
    ]
