# Generated by Django 4.0 on 2021-12-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gforms', '0002_remove_formmain_createdat_remove_formmain_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='userid',
        ),
    ]
