# Generated by Django 4.0 on 2021-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gforms', '0003_remove_question_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmain',
            name='usethisbool',
            field=models.BooleanField(default=False),
        ),
    ]
