# Generated by Django 4.0 on 2021-12-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gforms', '0004_formmain_usethisbool'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmain',
            name='createdby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
