# Generated by Django 4.0 on 2021-12-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gforms', '0005_formmain_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
